insert into ORDER_HEADER(ORDER_ID,ADDRESS,CUSTOMER_ID,ORDER_DATE,ORDER_STATUS,PRODUCT_ID,PRODUCT_NAME,QUANTITY,TOTAL_PRICE) values (1,'Chennai',1,'1/6/20','Shipped',1,'PhilipsTrimmer',1,800);  
insert into ORDER_HEADER(ORDER_ID,ADDRESS,CUSTOMER_ID,ORDER_DATE,ORDER_STATUS,PRODUCT_ID,PRODUCT_NAME,QUANTITY,TOTAL_PRICE) values (2,'Chennai',2,'4/6/20','ReadyToShip',2,'BeerShampoo',2,200);  
insert into ORDER_HEADER(ORDER_ID,ADDRESS,CUSTOMER_ID,ORDER_DATE,ORDER_STATUS,PRODUCT_ID,PRODUCT_NAME,QUANTITY,TOTAL_PRICE) values (3,'Chennai',2,'5/6/20','Packed',3,'OneplusHS',1,1900);  
 
