insert into INVENTORY_ENTITY(PRODUCT_ID,LOCATION,CITY,QUANTITY,STORE_ID) values (1,'Sholz','Chennai',10,1);
insert into INVENTORY_ENTITY(PRODUCT_ID,LOCATION,CITY,QUANTITY,STORE_ID) values (2,'Sholz','Chennai',13,1);
insert into INVENTORY_ENTITY(PRODUCT_ID,LOCATION,CITY,QUANTITY,STORE_ID) values (3,'Sholz','Chennai',11,1);
insert into INVENTORY_ENTITY(PRODUCT_ID,LOCATION,CITY,QUANTITY,STORE_ID) values (4,'Sholz','Chennai',15,1);
insert into INVENTORY_ENTITY(PRODUCT_ID,LOCATION,CITY,QUANTITY,STORE_ID) values (5,'Sholz','Chennai',2,1);